// Mocks generated by Mockito 5.4.6 from annotations
// in kpss_2026/test/unit/cubits/lesson_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kpss_2026/core/models/topic_explanation_model.dart' as _i6;
import 'package:kpss_2026/core/models/topic_model.dart' as _i4;
import 'package:kpss_2026/core/repositories/cached_explanation_repository.dart'
    as _i5;
import 'package:kpss_2026/core/repositories/topic_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TopicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicRepository extends _i1.Mock implements _i2.TopicRepository {
  MockTopicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TopicModel>> getTopicsByLesson(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getTopicsByLesson, [lessonId]),
            returnValue: _i3.Future<List<_i4.TopicModel>>.value(
              <_i4.TopicModel>[],
            ),
          )
          as _i3.Future<List<_i4.TopicModel>>);

  @override
  void clearCache([String? lessonId]) => super.noSuchMethod(
    Invocation.method(#clearCache, [lessonId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.TopicModel?> getTopicById(String? lessonId, String? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getTopicById, [lessonId, topicId]),
            returnValue: _i3.Future<_i4.TopicModel?>.value(),
          )
          as _i3.Future<_i4.TopicModel?>);

  @override
  List<_i4.TopicModel> getAllTopics() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTopics, []),
            returnValue: <_i4.TopicModel>[],
          )
          as List<_i4.TopicModel>);

  @override
  String? getTopicName(String? topicId) =>
      (super.noSuchMethod(Invocation.method(#getTopicName, [topicId]))
          as String?);
}

/// A class which mocks [CachedExplanationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCachedExplanationRepository extends _i1.Mock
    implements _i5.CachedExplanationRepository {
  MockCachedExplanationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.TopicExplanationModel?> getTopicExplanation(String? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getTopicExplanation, [topicId]),
            returnValue: _i3.Future<_i6.TopicExplanationModel?>.value(),
          )
          as _i3.Future<_i6.TopicExplanationModel?>);

  @override
  _i3.Future<void> clearCache(String? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [topicId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
